/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'pat' at '7/4/15 12:11 PM' with Gradle 2.4
 *
 * @author pat, @date 7/4/15 12:11 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
